<?php

require '../Include/Config.php';


// Services
require_once "../Services/projectorService.php";
require_once "../Services/webPowerSwitchService.php";


// This file is generated by Composer
require_once dirname(__FILE__) . '/../vendor/autoload.php';

use Slim\Slim;

Slim::registerAutoloader();

$app = new Slim();
$app->config('debug', false);

$app->contentType('application/json');

$app->error(function(Exception $e) use ($app) {
  $app->response->setStatus($e->getCode());
  echo json_encode(["error" => ["text" => $e->getMessage()]]);
});
/*
$app->container->singleton('projectorService', function () {
  return new projectorService();
});

$app->container->singleton('webPowerSwitchService', function () {
  return new webPowerSwitchService();
});
 */
 

$app->group('/devices', function () use ($app) {

  $app->post('/:deviceID', function ($deviceID) use ($app) {

    $input = getJSONFromApp($app);
  
  });

  $app->get('/:deviceID', function ($deviceID) use ($app) {
      $proj = new Projector();
      $proj->properties =  array("testing 123", "abcd");
      echo $proj->name;
      echo $proj->save();
      
  });

});


$app->run();

?>